lint:
  rules:
    no_default: false

  rules_option:
    max_line_length:
      max_chars: 120
      tab_chars: 2

  directories:
    exclude:
      - libs/proto-schema/dependencies
      - libs/proto-schema/external
